let mydate=new Date();
console.log(mydate);
console.log(mydate.toString());
console.log(mydate.toDateString());
console.log(mydate.toLocaleDateString());
let myDate= new Date(2023,1,15);
console.log(myDate.toDateString());
console.log(myDate.toLocaleDateString());
let date= new Date("2023-01-27");
console.log(date.toDateString());
console.log(date.toLocaleDateString());
let timestamp=  Date.now();
console.log(timestamp);
console.log(date.getTime());